
- name: Make *.pem to roles/api-server/files
  shell: cd /root/tmp/ansible-playbooks/ansible-k8s/roles/k8s-CA/files; cfssl_linux-amd64 gencert -initca ca-csr.json | cfssljson_linux-amd64 -bare ca -; cfssl_linux-amd64 gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes server-csr.json | cfssljson_linux-amd64 -bare server; cfssl_linux-amd64 gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson_linux-amd64 -bare kube-proxy; cfssl_linux-amd64 gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json |cfssljson_linux-amd64 -bare admin; cp *.pem /root/tmp/ansible-playbooks/ansible-k8s/roles/api-server/files; cd /root/tmp/ansible-playbooks/ansible-k8s/roles/api-server/files; ls *.pem;
  register: result
- name: Be sure CA success
  debug:
    var=result.stdout
